# Generated by Django 5.1.2 on 2024-10-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
